name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install and test User Service
      run: |
        cd user-service
        pip install -r requirements.txt
        pip install pytest
        pytest tests/

    - name: Install and test Room Service
      run: |
        cd room-service
        pip install -r requirements.txt
        pip install pytest
        pytest tests/

    - name: Install and test Reservation Service
      run: |
        cd reservation-service
        pip install -r requirements.txt
        pip install pytest
        pytest tests/

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build User Service
      uses: docker/build-push-action@v2
      with:
        context: ./user-service
        push: false
        tags: user-service:latest

    - name: Build Room Service
      uses: docker/build-push-action@v2
      with:
        context: ./room-service
        push: false
        tags: room-service:latest

    - name: Build Reservation Service
      uses: docker/build-push-action@v2
      with:
        context: ./reservation-service
        push: false
        tags: reservation-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Heroku
      uses: akshnz/heroku-cli-action@v1
      with:
        api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Login to Render
      run: |
        curl -fsSL https://render.com/deploy/script.sh | bash
        render login --api-key ${{ secrets.dep }}  # Use the 'dep' secret for Render API key

    - name: Deploy User Service to Render
      run: |
        render container:push web --service user-service --env production
        render container:release web --service user-service --env production

    - name: Deploy Room Service to Render
      run: |
        render container:push web --service room-service --env production
        render container:release web --service room-service --env production

    - name: Deploy Reservation Service to Render
      run: |
        render container:push web --service reservation-service --env production
        render container:release web --service reservation-service --env production
